language: c
script: asdf plugin-test telepresence https://github.com/bartoszmajsak/asdf-maistra.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
